language: ruby
rvm:
 - '2.2.0'

install:
 - npm install
 - npm install -g bower

before_script: bundle install; rake bower:install

script: RAILS_ENV=test rake db:create && RAILS_ENV=test rake db:migrate && RAILS_ENV=test rake spec&& RAILS_ENV=test rake teaspoon