language: ruby
rvm:
 - '2.3.0'

install:
 - npm install
 - npm install -g bower
 - npm install -g codeclimate-test-reporter
 
before_script:
 - bundle install
 - rake bower:install
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - RAILS_ENV=test rake db:create

script:
 - RAILS_ENV=test rake test

addons:
    code_climate:
        repo_token: c53f1607b65ec13555badf010d79408b2bb14ad9dff3bc495df5e72e534a0c2d
