language: ruby
rvm:
 - '2.3.0'

install:
 - npm install
 - npm install -g bower

before_script:
 - bundle install
 - rake bower:install
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - RAILS_ENV=test rake db:create

script:
 - RAILS_ENV=test rake test
